import { makeStyles } from "@material-ui/core";

export const useStyles = makeStyles((theme) => ({
    modal: {
      position: "absolute",
      overflow: "scroll",
      overflowX: "scroll",
      [theme.breakpoints.between("xs", "sm")]: {
        width: "50%",
        maxHeight: "80%",
      },
      [theme.breakpoints.up("md")]: {
        widht: "50%",
        maxHeight: "80%",
      },
      backgroundColor: theme.palette.background.paper,
      boxShadow: theme.shadows[5],
      padding: theme.spacing(3, 4, 5),
      top: "50%",
      left: "50%",
      transform: "translate(-50%, -50%)",
    },
    modalLoading: {
      position: "absolute",
      width: "25rem",
      backgroundColor: theme.palette.background.paper,
      // }border: '2px solid #000',
      borderRadius: "0.3rem",
      boxshadow: theme.shadows[5],
      padding: theme.spacing(2, 3, 3),
      top: "50%",
      left: "50%",
      transform: "translate(-50%, -50%)",
    },
    modal1: {
      position: "absolute",
      width: "23rem",
      height: "10rem",
      backgroundColor: theme.palette.background.paper,
      boxshadow: theme.shadows[5],
      padding: theme.spacing(3, 4, 5),
      top: "50%",
      left: "50%",
      transform: "translate(-50%, -50%)",
    },
    inputlarge: {
      overflow: "hidden",
      textOverflow: "ellipsis",
      width: "12rem",
      // [theme.breakpoints.up("lg")]: {
      //   width: "auto",
      // },
      [theme.breakpoints.between("md")]: {
        width: "100%",
      },
    },
    button_aceptar: {
      padding: "10px  12px 10px  12px",
      width: "100%",
      color: "black",
      backgroundColor: "#f09208",
      border: "1px solid black",
      borderRadius: "5%",
    },
    button_cancelar: {
      padding: "5px  12px 5px  12px",
      width: "100%",
      color: "white",
      backgroundColor: "#383837",
      border: "1px solid black",
      borderRadius: "5%",
    },
    error: {
      backgroundColor: "red",
      padding: "3px  4px 3px  4px",
      color: "white",
      textAlign: "center",
      borderRadius: "5px",
      marginBottom: "0.5rem",
      fontSize: "1rem",
    },
    texto: {
      flex: "1 1 0%",
      fontWeight: "600",
      color: "#4B5563",
      fontSize: "2rem",
      fontFamily: "Inter, sans-serif",
      textAlign: "center",
    },
  }));